### ISSUE TITLE
Generalization/cleanup

### ISSUE THREAD

**Issue by MegaphoneJon** [krd-consulting/ncn-civi-zoom#1]
Hi Rupert,

I've been looking at this extension - it's pretty cool, and very timely!  I was wondering if you'd be willing to incorporate PRs back to generalize this, or if you'd prefer I fork.

I was thinking I'd move the environment variables into Civi's settings and generate a custom field on install for the Zoom webinar ID (and remove references to `custom_48`).  I may find other things, but those are the big two.  I think that's all that would be necessary for this to be usable by other organizations.

Also, one curiosity - I see you have some dependencies (notably Guzzle) that are also supplied by CiviCRM.  Is there a versioning issue, or can we use the Civi versions?

**Comment by rupertraphael** [comment]
Hi Jon,

Yeah, generalizing it, removing our own references to custom fields, and using CiviCRM settings instead of .env files would be great! Although, I think I’d be better for the both of us if you fork it as I think I won’t be able to attend to the PRs if you submit some (or I could but I won't be reviewing them very leniently). (Doing another time critical project for another client.) Although, I'd be happy to answer any questions to help you develop your Civi-Zoom integration.

On the Guzzle dependency, I’m using [Zttp](https://github.com/kitetail/zttp) on top of it as I find it simpler to use. But, I think, using the one that comes with Civi should be fine. 

I just pushed some changes (that I forgot to push) as I was writing this reply and those changes included deleting the extension’s Guzzle instance in order to force it to use Civi’s Guzzle instance (not sure if this is the way to do it).

EDIT: Also, not really necessary, but allowing this extension to create web hooks in behalf of the client would also be a great addition so that they don't have to manually set web hooks in their Zoom Developer Settings.

**Comment by MegaphoneJon** [comment]
Sounds great Rupert!  I'll go back to my own client and see if the funding is for sure there.  I'll let you know if I fork it, and thanks for the offer to answer questions.  -J

**Comment by MegaphoneJon** [comment]
Just wanted to report back that both of my clients have backed off the Zoom integration for now - but I'm going to mention the surge in interest when I'm interviewed next week for a podcast whose topic is database management and COVID-19.  Maybe it'll drum up some interest when I promote the podcasts to my clients.

**Comment by rupertraphael** [comment]
Thanks so much for the update, @MegaphoneJon 

And mentioning this to the podcast would be great! I hope someone gets the opportunity to make a more robust version of this extension
